### ISSUE TITLE
Transfer end-use sector and material classifications

### ISSUE THREAD

**Issue by stefanpauliuk** [stefanpauliuk/CIRCOMOD_WP2_DATA#1]
@chauenstein please transfer end-use sector and material classifications (2 tables in the vision and scoping document) to the project's master classification file CIRCOMOD_Project_Wide_Classifications.xlsx
Ca. by mid June.

**Comment by chauenstein** [comment]
@stefanpauliuk: I have added the two classifications to the master classification file. Additionally, I added a copy of the iedc_2_items to the master classification file (which was missing so far). 
Could you check the added classifications before I close this issue? Thank you.

**Comment by stefanpauliuk** [comment]
Thanks @chauenstein , looks all good!
The iecd_2 classification items are probably not up to date (did you take [IEDC_2_regions_ISO_3166_V1.0.xlsx](https://github.com/IndEcol/SEM_classifications/blob/master/regions/IEDC_2_regions_ISO_3166_V1.0.xlsx)?, here only the items in the MySQL database are complete, so we can download and update this classification as yaml file later.

**Comment by chauenstein** [comment]
Thanks @stefanpauliuk. For the iecd_2 classification I copied the content of classification item 'regions_iso_iedc' from https://www.database.industrialecology.uni-freiburg.de/classifications.aspx (is that what you referred with the MySQL database?)
